// Javascript for implementhing those 3 problems from Project Euler
	// https://projecteuler.net/problem=1
	// https://projecteuler.net/problem=2
	// https://projecteuler.net/problem=3


function Problem(title,subtitle,description)
{
	this.title = title;
	this.subtitle = subtitle;
	this.description = description;
}



var problem1 = new Problem("Multiples of 3 and 5","Problem 1","If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.");

var problem2 = new Problem("Even Fibonacci numbers","Problem 2","Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacc sequence whose values do not exceed four million, find the sum of the even-valued terms.");

var problem3 = new Problem("Larges prime factor","Problem 3","The prime factors of 13195 are 5, 7, 13 and 29.What is the largest prime factor of the number 600851475143 ?");

function start(){
	var para = document.createElement("p");
	var node = document.createTextNode("This is new.");
	para.appendChild(node);

	var element = document.getElementById("div1");
	element.appendChild(para);
}
